language: java

sudo: required

services:
  - docker

cache:
  directories:
  - ${HOME}/.cache
  - ${HOME}/.m2
  - ${HOME}/google-cloud-sdk

script:
  - ./ci/build.sh && ./ci/deploy.sh

after_failure:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml logs