language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh && ./ci/deploy.sh

after_failure:
  - docker-compose -f k8s/keycloak-ha-mysql/docker-compose.yml -f k8s/keycloak-ha-mysql/docker-compose.ci.yml logs