version: "3"
services:

  db:
   ports:
     - 3306:3306

  keycloak1:
    build: .
    volumes:
      - ./theme/akvo:/opt/jboss/keycloak/themes/akvo
    ports:
    - 8080:8080

  metrics:
    ports:
    - 8888:8888

  tests:
    ports:
       # REPL
       - "47480:47480"
